
.PHONY: icons

# Various icon sizes.
icons: icon.png
	~/mine/make_xcode_icons/make_xcode_icons icon.png ../r_view/Assets.xcassets/AppIcon.appiconset

# Master icon.
icon.png: make_icon
	./make_icon icon.png

